//! Keeping a repo's `AGENTS.md` in sync with its branch.
//!
//! `AGENTS.md` on disk is the floor (spec §9): it works for teammates without
//! RecurOS installed and survives every hook bug. We own only the region
//! between our markers, so a hand-written `AGENTS.md` is never clobbered.

use std::fs;
use std::path::Path;

use anyhow::Result;
use ctx_pack::Projection;

use crate::{App, PackOpts};

pub const BEGIN: &str = "<!-- ctx:begin (generated by RecurOS: edit with `ctx`, not by hand) -->";
pub const END: &str = "<!-- ctx:end -->";

/// Replace (or append) the marked region in `existing` with `block`.
pub fn splice(existing: &str, block: &str) -> String {
    let region = format!("{BEGIN}\n{}{END}\n", ensure_newline(block));
    match (existing.find(BEGIN), existing.find(END)) {
        (Some(b), Some(e)) if e > b => {
            let after = &existing[e + END.len()..];
            let after = after.strip_prefix('\n').unwrap_or(after);
            format!("{}{region}{after}", &existing[..b])
        }
        _ if existing.trim().is_empty() => region,
        _ => format!("{}\n{region}", ensure_newline(existing)),
    }
}

fn ensure_newline(s: &str) -> String {
    if s.ends_with('\n') {
        s.to_owned()
    } else {
        format!("{s}\n")
    }
}

/// The current generated region of `AGENTS.md`, if present.
pub fn current_block(existing: &str) -> Option<&str> {
    let b = existing.find(BEGIN)? + BEGIN.len();
    let e = existing.find(END)?;
    (e > b).then(|| existing[b..e].trim_start_matches('\n'))
}

impl App {
    /// Recompile the bound branch's pack into `<repo>/AGENTS.md`. Returns the
    /// new block if the file changed, `None` if it was already current or
    /// this directory isn't bound to a branch.
    pub fn refresh_agents_md(&self) -> Result<Option<String>> {
        let Some(binding) = &self.binding else {
            return Ok(None);
        };
        let pack = self.pack(&PackOpts {
            branch: Some(binding.branch_ref()?.to_string()),
            projection: Some(Projection::AgentsMd),
            ..Default::default()
        })?;
        // Keep the agent-facing command list current alongside AGENTS.md.
        let commands = binding.root.join(".ctx").join("commands.md");
        if fs::read_to_string(&commands).ok().as_deref() != Some(crate::COMMANDS_MD) {
            if let Some(dir) = commands.parent() {
                fs::create_dir_all(dir)?;
            }
            fs::write(&commands, crate::COMMANDS_MD)?;
        }
        let path = binding.root.join("AGENTS.md");
        let existing = fs::read_to_string(&path).unwrap_or_default();
        if current_block(&existing) == Some(pack.markdown.as_str()) {
            return Ok(None);
        }
        fs::write(&path, splice(&existing, &pack.markdown))?;
        Ok(Some(pack.markdown))
    }
}

/// Whether `dir/AGENTS.md` has a RecurOS region.
pub fn has_block(dir: &Path) -> bool {
    fs::read_to_string(dir.join("AGENTS.md")).is_ok_and(|s| current_block(&s).is_some())
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn splice_preserves_user_content() {
        let user = "# My project\n\nRun `make test`.\n";
        let once = splice(user, "ctx stuff\n");
        assert!(once.starts_with(user));
        assert_eq!(current_block(&once), Some("ctx stuff\n"));
        let twice = splice(&once, "new stuff\n");
        assert!(twice.starts_with(user));
        assert_eq!(current_block(&twice), Some("new stuff\n"));
        assert_eq!(twice.matches(BEGIN).count(), 1);

        let with_tail = format!("{once}\n## Tail\n");
        let replaced = splice(&with_tail, "x\n");
        assert!(replaced.ends_with("\n## Tail\n"), "{replaced}");
        assert_eq!(splice("", "x"), format!("{BEGIN}\nx\n{END}\n"));
    }
}
