//! Documents (specs) and the idea-to-build flow.
//!
//! The flow this module serves:
//!
//! 1. `ctx new <idea>` creates the project and makes its research branch
//!    the active one, so chat surfaces (Worker, extension, clipboard) write
//!    there by default.
//! 2. Research happens in claude.ai or ChatGPT and lands as claims.
//! 3. The research ends with a spec: a long markdown document saved as a
//!    `doc` record named `spec`.
//! 4. `ctx build <idea>` creates a code repo bound to `<idea>/code`, which
//!    inherits the research conclusions, and writes the spec to `SPEC.md`
//!    so a coding agent can start from it immediately.

use std::fs;
use std::path::Path;
use std::time::SystemTime;

use anyhow::{Result, bail};
use chrono::{DateTime, Utc};
use ctx_core::canonical::normalize_text;
use ctx_core::{BranchRef, Doc, Record, Store, tokens};
use ctx_pack::DocRef;
use ulid::Ulid;

use crate::App;

/// Name of the document `ctx build` hands to coding agents.
pub const SPEC: &str = "spec";
/// File the spec is written to inside a bound repo.
pub const SPEC_FILE: &str = ".ctx/SPEC.md";
/// Where the spec was written before `.ctx/` existed.
const LEGACY_SPEC_FILE: &str = "SPEC.md";

const MARKER_PREFIX: &str = "<!-- ctx:doc ";

/// Outcome of saving a document.
#[derive(Debug)]
pub struct DocSaved {
    pub doc: Doc,
    /// True when the current version already had this exact body, so
    /// nothing was written.
    pub duplicate: bool,
}

/// What happened to `SPEC.md` during a refresh.
#[derive(Debug, PartialEq, Eq)]
pub enum SpecFile {
    /// No spec exists for this project yet, or the repo isn't bound.
    NoSpec,
    Written,
    Unchanged,
    /// The file was edited by hand (or isn't ours), so it was left alone.
    LeftAlone,
}

fn marker(doc: &Doc) -> String {
    format!(
        "{MARKER_PREFIX}name={} cid={} branch={} (generated by RecurOS; to change it, save a new version with `ctx spec save`) -->",
        doc.name, doc.cid, doc.branch
    )
}

/// Parse our marker line: returns the recorded cid.
fn marker_cid(first_line: &str) -> Option<&str> {
    let rest = first_line.strip_prefix(MARKER_PREFIX)?;
    rest.split_whitespace()
        .find_map(|kv| kv.strip_prefix("cid="))
}

impl App {
    /// Save a new version of a document. Identical content to the current
    /// version is a no-op, so re-saving the same spec is harmless.
    pub fn save_doc(
        &mut self,
        branch: &BranchRef,
        name: &str,
        title: Option<&str>,
        body: &str,
        src: &str,
    ) -> Result<DocSaved> {
        let sys = SystemTime::now();
        let at: DateTime<Utc> = sys.into();
        let doc = Doc::new(
            Ulid::from_datetime(sys),
            branch.clone(),
            name,
            title,
            body,
            src,
            at,
        )?;
        if let Some(current) = self.store.doc(branch, &doc.name)?
            && current.cid == doc.cid
        {
            return Ok(DocSaved {
                doc: current,
                duplicate: true,
            });
        }
        shard_append(self, Record::Doc(doc.clone()), at)?;
        Ok(DocSaved {
            doc,
            duplicate: false,
        })
    }

    /// Find a document for `branch`: on the branch itself, then on the
    /// branches it inherits from, then anywhere in the same project. This is
    /// how a code branch finds the spec its research branch produced.
    pub fn find_doc(&self, branch: &BranchRef, name: &str) -> Result<Option<Doc>> {
        if let Some(d) = self.store.doc(branch, name)? {
            return Ok(Some(d));
        }
        for src in self.branches.pool_sources(branch) {
            if let Some(d) = self.store.doc(&src.branch, name)? {
                return Ok(Some(d));
            }
        }
        let Some((project, _)) = branch.as_str().split_once('/') else {
            return Ok(None);
        };
        Ok(self
            .store
            .docs(None)?
            .into_iter()
            .filter(|d| d.name == name && d.branch.as_str().starts_with(&format!("{project}/")))
            .max_by_key(|d| d.id))
    }

    /// Documents visible from `branch` (own and inherited), one per name.
    pub fn visible_docs(&self, branch: &BranchRef) -> Result<Vec<Doc>> {
        let mut out: Vec<Doc> = Vec::new();
        let mut branches = vec![branch.clone()];
        branches.extend(
            self.branches
                .pool_sources(branch)
                .into_iter()
                .map(|s| s.branch),
        );
        for b in branches {
            for d in self.store.docs(Some(&b))? {
                if !out.iter().any(|o| o.name == d.name) {
                    out.push(d);
                }
            }
        }
        // A code branch should see its project's spec even when the spec was
        // saved on a branch it doesn't inherit from.
        if !out.iter().any(|d| d.name == SPEC)
            && let Some(spec) = self.find_doc(branch, SPEC)?
        {
            out.push(spec);
        }
        Ok(out)
    }

    /// Document references for a pack: where each one can be read in full.
    pub fn doc_refs(&self, branch: &BranchRef) -> Result<Vec<DocRef>> {
        let bound_here = self
            .binding
            .as_ref()
            .and_then(|b| b.branch_ref().ok())
            .is_some_and(|b| &b == branch);
        Ok(self
            .visible_docs(branch)?
            .into_iter()
            .map(|d| DocRef {
                location: if d.name == SPEC && bound_here {
                    format!("`{SPEC_FILE}`")
                } else {
                    format!("`ctx spec show {}` or ctx_pack(doc=\"{}\")", d.name, d.name)
                },
                tokens: tokens::estimate(&d.body),
                title: d.title,
                name: d.name,
            })
            .collect())
    }

    /// `ctx new <idea>`: create the project (research + code branches) and
    /// make its research branch active for chat surfaces.
    pub fn new_project(&mut self, project: &str) -> Result<BranchRef> {
        let research = BranchRef::new(&format!("{project}/research")).map_err(|_| {
            anyhow::anyhow!(
                "invalid project name `{project}`: use lowercase letters, digits and '-'"
            )
        })?;
        self.ensure_project(project, "code")?;
        self.set_active(&research)?;
        Ok(research)
    }

    /// Write the project's spec to `SPEC.md` in the bound repo, unless the
    /// file was edited by hand or is not ours. A marker on the first line
    /// records which version we wrote, so hand edits are detected by
    /// comparing the file's content with that version.
    pub fn refresh_spec_file(&self) -> Result<SpecFile> {
        let Some(binding) = &self.binding else {
            return Ok(SpecFile::NoSpec);
        };
        let Some(doc) = self.find_doc(&binding.branch_ref()?, SPEC)? else {
            return Ok(SpecFile::NoSpec);
        };
        let path = binding.root.join(SPEC_FILE);
        // A root SPEC.md we wrote and nobody edited has moved into .ctx/.
        let legacy = binding.root.join(LEGACY_SPEC_FILE);
        if let Ok(old) = fs::read_to_string(&legacy) {
            let (first, rest) = old.split_once('\n').unwrap_or((old.as_str(), ""));
            if marker_cid(first)
                .is_some_and(|c| ctx_core::record::doc_cid(&normalize_text(rest)) == c)
            {
                let _ = fs::remove_file(&legacy);
            }
        }
        if let Some(dir) = path.parent() {
            fs::create_dir_all(dir)?;
        }
        let wanted = format!("{}\n{}\n", marker(&doc), doc.body);
        match fs::read_to_string(&path) {
            Err(_) => {}
            Ok(existing) => {
                if existing == wanted {
                    return Ok(SpecFile::Unchanged);
                }
                let (first, rest) = existing.split_once('\n').unwrap_or((existing.as_str(), ""));
                let Some(recorded) = marker_cid(first) else {
                    return Ok(SpecFile::LeftAlone); // someone else's SPEC.md
                };
                if ctx_core::record::doc_cid(&normalize_text(rest)) != recorded {
                    return Ok(SpecFile::LeftAlone); // edited by hand
                }
            }
        }
        fs::write(&path, wanted)?;
        Ok(SpecFile::Written)
    }
}

fn shard_append(app: &mut App, record: Record, at: DateTime<Utc>) -> Result<()> {
    ctx_git::shard::append(&app.home, app.machine(), &record, at)?;
    app.catch_up()
}

/// Extract a spec from pasted text: the body of a ````ctx-spec fence (any
/// fence of three or more backticks or tildes tagged ctx-spec), or the whole
/// text if there is no such fence.
pub fn parse_spec_block(text: &str) -> Result<String> {
    let lines: Vec<&str> = text.lines().collect();
    let mut start = None;
    let mut fence = String::new();
    for (i, l) in lines.iter().enumerate() {
        let t = l.trim_start();
        let marker: String = t.chars().take_while(|c| *c == '`' || *c == '~').collect();
        if marker.len() >= 3 && t[marker.len()..].trim() == "ctx-spec" {
            start = Some(i + 1);
            fence = marker;
            break;
        }
    }
    let body = match start {
        Some(s) => {
            let end = lines[s..]
                .iter()
                .position(|l| l.trim() == fence)
                .map(|e| s + e)
                .unwrap_or(lines.len());
            lines[s..end].join("\n")
        }
        None => text.to_owned(),
    };
    if body.trim().is_empty() {
        bail!("the spec is empty");
    }
    Ok(body)
}

/// Whether a directory looks empty enough to create a project in.
pub fn is_empty_dir(dir: &Path) -> bool {
    fs::read_dir(dir)
        .map(|mut d| d.next().is_none())
        .unwrap_or(true)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn spec_block_keeps_nested_fences() {
        let text =
            "Here it is:\n\n````ctx-spec\n# Idea\n\n```rust\nfn main() {}\n```\n````\nThanks";
        assert_eq!(
            parse_spec_block(text).unwrap(),
            "# Idea\n\n```rust\nfn main() {}\n```"
        );
        assert_eq!(
            parse_spec_block("# Just markdown").unwrap(),
            "# Just markdown"
        );
        assert!(parse_spec_block("````ctx-spec\n\n````").is_err());
    }

    #[test]
    fn marker_round_trip() {
        let d = Doc::new(
            Ulid::nil(),
            BranchRef::new("p/research").unwrap(),
            "spec",
            None,
            "# X",
            "cli",
            DateTime::<Utc>::UNIX_EPOCH,
        )
        .unwrap();
        assert_eq!(marker_cid(&marker(&d)), Some(d.cid.as_str()));
        assert_eq!(marker_cid("# not ours"), None);
    }
}
